### ISSUE TITLE
这个分类怎么使用?

### ISSUE THREAD

**Issue by BestKai** [tbl00c/UICollectionView-EmptyFix#1]
我也遇到了部分item不显示的问题，这个分类怎么使用、？我直接引入不起作用

**Comment by tbl00c** [comment]
如果是同一个问题，直接引入就可以

**Comment by yunkai909** [comment]
嗯，我的不是这个原因。是因为某个section的item个数不为0，但是sizeforitem设为了cgsizezero造成的空白。
